version: '3'
services:
  postgres:
    image: "postgres:latest"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - dbdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
volumes:
  dbdata:
